### ISSUE TITLE
Consider x86 (32 bit) support.

### ISSUE THREAD

**Issue by KanhaKanhaiya** [Alex313031/codium#11]
Since Microsoft has abandoned the support for VSCode on x86 (32 bit) Windows, it has left many users who use 32 bit Windows unable to update it. I know that there are very few 32 bit users as compared to 64 bit users but as this repo strives to achieve backward compatibility thus considering to support 32 bit Windows will be a great option for many.

The README mentions x86 support but the corresponding exe is not mentioned in the latest release : https://github.com/Alex313031/codium/releases/tag/1.89.1.24132

Apologies for any mistakes. Kindly inform if there is a way to use the latest version on Windows 7 x86. If not, please support it.

**Comment by Alex313031** [comment]
@KanhaKanhaiya I can try to revert the commit where they removed 32 bit support.

**Comment by KanhaKanhaiya** [comment]
👍🏻🎉 Please do so 👍🏻

**Comment by Alex313031** [comment]
@KanhaKanhaiya Found it. Kinda pisses me off. It was a completely artificial limitation. All the native modules, as well as NodeJS and Electron itself still support 32 bit Windows just fine. They just removed the build config files for it. No real reason they had to discontinue support except as a fuck you to users, and part of their decisions over the last two years that seem to have the overarching goal of forcing users onto new hardware with Windows 11.

They removed it after 1.83.1. 
Once I restore it, this will make Codium not only the only Win7/8/8.1 compatible VSCode fork, but also the only 32 bit compatible fork.

The specific commit I need to revert is this > https://github.com/microsoft/vscode/commit/9905225b1ac83292f6a4ed08debfe29cad5ece4e

I will start with just re-adding the lines back, and then I will probably have to tweak some things since the code has changed alot since then.

Thanks for bringing this to my attention! This is my most popular Electron app, and my second most popular Windows 7 compatible app (behind Thorium). All my Windows 7/8 compatible apps have 32 bit builds, yet for some reason that slipped my mind for this repo. Obviously many win7/8 users (and Windows 10 users too, which is another reason I'm scratching my head about Microsoft), are on 32 bit platforms. Oftentimes, using 32 bit Windows even on modern 64 bit chips, because they need 32 bit support for 16 bit MS-DOS programs, or old programs that expect 32 bit NT.
Assuming a successful reversion of that commit (which I'm almost positive I can do), Codium will have 32 bit Windows builds going forward.

Happy Coding!

**Comment by KanhaKanhaiya** [comment]
Thank You 👍

The 32 bit Windows community is highly grateful to you.

Keep it up 👍

**Comment by Alex313031** [comment]
@KanhaKanhaiya Fixed.

Here you go > https://github.com/Alex313031/codium/releases/tag/1.89.1.24138

**Comment by KanhaKanhaiya** [comment]
Wowwww....

Thank You So Much for this awesome port. Really you are one of the few people working for the 32 bit community  👍🏻

**Comment by eggzist** [comment]
What a great comunity
