### ISSUE TITLE
Node.js dropped support for Windows 7 long ago. Is there a way to use the version used in Codium?

### ISSUE THREAD

**Issue by huseeiin** [Alex313031/codium#12]
You must be using a modern version of Node to make this work, right? can we get it? Not an issue, just a question.

**Comment by n0099** [comment]
https://github.com/Alex313031/node16-win7

**Comment by Alex313031** [comment]
@huseeiin @n0099 Yes, Node 14 and 16 can be used on Windows 7, with some minor patching. See the repo that n0099 linked. However, I have yet to make some release builds, because I need to clear up some space on my Windows 10 drive. For most of my Windows projects, I either cross build on Linux, or build them in a VM. But this requires me to download and build the large repo on a real machine.

Codium uses Node 16.17.1 and Electron 22.3.27. 

When I make public releases of node16-win7, I will let y'all know here.

I also saw a repo where someone got Node 18 workin on Win7, but it looked like he had to disable openSSL and bash support. So 16 seems to be the highest version that one can build with all the features enabled/working.

**Comment by Alex313031** [comment]
@n0099 @huseeiin Released builds of Node 16 and 18 for Windows 7+

https://github.com/Alex313031/node16-win7/releases

https://github.com/Alex313031/node18-win7/releases

**Comment by huseeiin** [comment]
> @n0099 @huseeiin Released builds of Node 14, Node 16, and 18 for Windows 7+
> 
> https://github.com/Alex313031/node14-win7/releases https://github.com/Alex313031/node16-win7/releases https://github.com/Alex313031/node18-win7/releases

Huge! thanks. Node 20?

**Comment by Alex313031** [comment]
@huseeiin Node 20 requires alot more work to patch for windows 7.  It also doesn't really make sense. There aren't any projects out there that I am aware of that use Node 20, and that could still run or be built on Windows 7.

**Comment by huseeiin** [comment]
> @huseeiin Node 20 requires alot more work to patch for windows 7. It also doesn't really make sense. There aren't any projects out there that I am aware of that use Node 20, and that could still run or be built on Windows 7.

fair. i will close this.
